### ISSUE TITLE
Controller in another file

### ISSUE THREAD

**Issue by bkcan** [dkhamsing/DKScrollingTabController#10]
I'm trying to put a DKScrollingTabController in its own class, `DKViewController : DKScrollingTab Controller` instead of with the `MainViewController`.

The issue is that the `UIButtons` doesn't show in the main view controller. When I press in the section it's suppose to be showing in, the delegate responds. I also `NSLog` buttons array and it has all the buttons I want.

Could this maybe be a thread issue?

**Note** All of the code is the same when transferring from the `MainViewController` to `DKViewController`

**Comment by dkhamsing** [comment]
Can you share your code or project

**Comment by bkcan** [comment]
**DKGroupViewController.h**

     #import <UIKit/UIKit.h>
     #import "DKGroupViewController.h"
     #import <DKScrollingTabController.h>
     @interface DKGroupViewController : UIViewController

    - (DKScrollingTabController *)groupScrollingTabController;

**DKGroupViewController.m**
   
    #import "DKGroupViewController.h"
    #import "RZEThemeManager.h"

    @interface DKGroupViewController ()

    @end

    @implementation DKGroupViewController

    - (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    }

    - (void)didReceiveMemoryWarning {
        [super didReceiveMemoryWarning];
        // Dispose of any resources that can be recreated.
    }

    - (DKScrollingTabController *)groupScrollingTabController {
         DKScrollingTabController *groupTabController = [[DKScrollingTabController alloc] init];
    
        groupTabController.view.backgroundColor = [UIColor blackColor]
        groupTabController.unselectedBackgroundColor = [UIColor clearColor];
        groupTabController.selectedBackgroundColor = [UIColor clearColor];
        groupTabController.buttonPadding = 40; // button width
        groupTabController.underlineIndicator = YES;
        groupTabController.underlineIndicatorColor = [UIColor whiteColor];
        groupTabController.buttonsScrollView.showsHorizontalScrollIndicator = NO;
        groupTabController.selectedTextColor = [UIColor whiteColor];
        groupTabController.unselectedTextColor = [UIColor whiteColor];
        groupTabController.startingIndex = 0;
        groupTabController.buttonTitleEdgeInsets = UIEdgeInsetsMake(10, 0, 10, 0);
        groupTabController.selection = @[@"PLACE\n0"];
        [groupTabController setButtonName:@"All" atIndex:0];
       
        return groupTabController;
     }

**MainViewController.m**

     groupTabController1 = [[DKGroupScrollingTabController alloc] init];
     groupTabController1 = [[DKGroupScrollingTabController alloc] groupDKScrollingTabController];
    
     groupTabController1.delegate = self;
     [self addChildViewController:groupTabController1];
     [groupTabController1 didMoveToParentViewController:self];
     [self.view addSubview:groupTabController1.view];
     groupTabController1.view.frame = CGRectMake(0, 60, self.view.bounds.size.width, 44);
    
     for (UIButton *button in groupTabController1.buttons) {
        button.titleLabel.numberOfLines = 3;
        button.titleLabel.textAlignment = NSTextAlignmentCenter;
        
        NSString *buttonName = button.titleLabel.text;
        NSString *text = buttonName;
        NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:buttonName];
        NSDictionary *attributes = @{ NSFontAttributeName : [UIFont systemFontOfSize:12] };
        NSRange range = [buttonName rangeOfString:text];
        [attributedString addAttributes:attributes range:range];
        
        button.titleLabel.text = @"";
        [button setAttributedTitle:attributedString forState:UIControlStateNormal];
    }

**Comment by dkhamsing** [comment]
Thank you

Hmm I see

The way DKScrollingTabController is supposed to be added is through view controller containment https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html

So it should not be in the interface, just added to the implementation file, just like in the demo https://github.com/dkhamsing/DKScrollingTabController/blob/master/Demo-Objc/Demo/ViewControllerSimple.m

Does this help?

**Comment by bkcan** [comment]
I am implementing DKScrollingTabController as a view controller containment. The only thing that is messing up is when I'm fixing up all the UIButtons in the for-loop/enumeratingBlocks. I've tried to put it in the `DKGroupViewController.m` and then `MainViewController.m` but they both give me the same result. 

**Note** I just left all the code in `MainViewController.m` and everything works. I would just like to have  `MainViewController.m` cleaned up and also I would like to use `DKGroupViewController.m` in other files so that I don't have to keep repeating the same code.

**Comment by dkhamsing** [comment]
Hm I see

If things are ok when you leave them in MainViewController, then the issue is probably in DKGroupViewController: 

- Looks like you are adding groupTabController1 to MainViewController
- But you are not adding groupTabController  in DKGroupScrollingTabController: try that

I'm not sure how you are using the control but maybe it should not be repeated.. really depends on what you want to accomplish

Ideally it is created once and displayed once, tapping a button would load up something else.
