### ISSUE TITLE
Underline Indicator not visible

### ISSUE THREAD

**Issue by cristinaITdeveloper** [dkhamsing/DKScrollingTabController#14]
Hi!
Nice library! I use it in my project, in this way:

        
    
        tabController.delegate = self
        tabController.buttonPadding = 25
        tabController.unselectedBackgroundColor = UIColor.groupTableViewBackgroundColor()
        tabController.selectionFont = mainFont
        tabController.unselectedTextColor = UIColor.grayColor()
        tabController.selectedBackgroundColor = UIColor.groupTableViewBackgroundColor()
        tabController.selectedTextColor = mainColor
        tabController.underlineIndicator = true
        tabController.underlineIndicatorColor = mainColor
        tabController.underlineIndicatorOffset = 20

But the underline Indicator is not showed.
Can you help me?
Thank you.

**Comment by dkhamsing** [comment]
You have to make sure all the customizations happen before 

> tabcontroller.selection = //...

**Comment by xuanzi23** [comment]
@cristinaITdeveloper i facing same problem with u also. How u solve this?
