### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by mhernandez91** [dkhamsing/DKScrollingTabController#5]
Hi, I'm trying to use this library on swift but it has been nearly impossible due to the name of the delegate method. Basically, any delegate method name beginning in "DKScrollingTabController: ..." will mess the type "DKScrollingTabController" leaving it unusable even for the controller parameter in the delegate method.

Also fyi: if anyone else is trying to implement this library in swift you should follow this order
1- Visual configuration of the controller
2- Adding the subview to the parent
 3- Assign the frame
 4- Assign tab items

Any other orders (at least the ones I've tried) had visual issues when the view is displayed

**Comment by dkhamsing** [comment]
:confused: 

so you were able to use it or no? will take a look

**Comment by dkhamsing** [comment]
I looked into this, the `DKScrollingTabControllerDelegate` method name cannot start with DKScrollingTabController.. will update the library
